"""Sound library: manages the sounds/ folder and sounds.json manifest."""
from __future__ import annotations

import json
import shutil
import uuid
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
SOUNDS_DIR = APP_DIR / "sounds"
MANIFEST = SOUNDS_DIR / "sounds.json"

ALLOWED_EXT = {".wav", ".mp3", ".ogg", ".flac", ".oga"}

# Starter pack: (display name, filename in sounds/). Files are generated by
# scripts/make_starter_sounds.py on first setup if missing.
STARTER = [
    ("Cheers", "cheers.wav"),
    ("Applause", "applause.wav"),
    ("Airhorn", "airhorn.wav"),
]


class Sound:
    __slots__ = ("id", "name", "file")

    def __init__(self, id: str, name: str, file: str):
        self.id = id
        self.name = name
        self.file = file  # basename inside SOUNDS_DIR

    @property
    def path(self) -> Path:
        return SOUNDS_DIR / self.file

    def to_dict(self) -> dict:
        return {"id": self.id, "name": self.name, "file": self.file}


class Library:
    def __init__(self) -> None:
        SOUNDS_DIR.mkdir(parents=True, exist_ok=True)
        self.sounds: list[Sound] = []
        self._load()

    # ---- persistence -------------------------------------------------
    def _load(self) -> None:
        if MANIFEST.exists():
            try:
                data = json.loads(MANIFEST.read_text())
            except (json.JSONDecodeError, OSError):
                data = []
            self.sounds = [
                Sound(s.get("id") or uuid.uuid4().hex, s["name"], s["file"])
                for s in data
                if (SOUNDS_DIR / s.get("file", "")).exists()
            ]
        else:
            self._seed_starter()
        # Persist any pruning/seeding.
        self._save()

    def _seed_starter(self) -> None:
        self.sounds = [
            Sound(uuid.uuid4().hex, name, fname)
            for name, fname in STARTER
            if (SOUNDS_DIR / fname).exists()
        ]

    def _save(self) -> None:
        MANIFEST.write_text(json.dumps([s.to_dict() for s in self.sounds], indent=2))

    # ---- operations --------------------------------------------------
    def add(self, src: str | Path) -> Sound:
        src = Path(src)
        if src.suffix.lower() not in ALLOWED_EXT:
            raise ValueError(f"Unsupported file type: {src.suffix}")
        if not src.is_file():
            raise ValueError(f"Not a file: {src}")
        # Copy into sounds/ with a unique-ish name to avoid clobbering.
        dest_name = src.name
        dest = SOUNDS_DIR / dest_name
        if dest.exists():
            dest_name = f"{src.stem}-{uuid.uuid4().hex[:6]}{src.suffix}"
            dest = SOUNDS_DIR / dest_name
        shutil.copy2(src, dest)
        snd = Sound(uuid.uuid4().hex, src.stem, dest_name)
        self.sounds.append(snd)
        self._save()
        return snd

    def remove(self, sound_id: str) -> None:
        snd = next((s for s in self.sounds if s.id == sound_id), None)
        if snd is None:
            return
        self.sounds = [s for s in self.sounds if s.id != sound_id]
        # Delete the file only if no other entry references it.
        if not any(s.file == snd.file for s in self.sounds):
            try:
                snd.path.unlink(missing_ok=True)
            except OSError:
                pass
        self._save()
